services:
  snc-biometrics-cms:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    image: strapi/strapi
    container_name: snc-bio-cms-dev
    ports:
      - 1338:1338
    environment:
      NODE_ENV: development      
      DATABASE_CLIENT: postgres
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5432
      DATABASE_NAME: snc_bio
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: snc2004
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      TZ: Asia/Kuala_Lumpur
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - strapi-net
networks:
  strapi-net: 

